# Generated by Django 3.2.7 on 2021-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/products/images/')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
